### ISSUE TITLE
CodeBase is not supported on assemblies loaded from a single-file bundle

### ISSUE THREAD

**Issue by marcosgerene** [OpenAC-Net/OpenAC.Net.Core#1]
Em produção minha aplicação recebe o seguinte erro:
```
Message:CodeBase is not supported on assemblies loaded from a single-file bundle.
Stack Trace:    at System.Reflection.RuntimeAssembly.getCodeBase()
   at OpenAC.Net.Core.Extensions.AssemblyExtenssions.GetPath(Assembly ass) in E:\Programacao\OpenAC .Net\OpenAC.Net.Core\src\OpenAC.Net.Core\Extensions\AssemblyExtenssions.cs:line 49
   at OpenAC.Net.NFSe.Configuracao.ConfigArquivosNFSe..ctor() in //src/OpenAC.Net.NFSe/Configuracao/ConfigArquivosNFSe.cs:line 52
   at OpenAC.Net.NFSe.Configuracao.ConfigNFSe..ctor() in //src/OpenAC.Net.NFSe/Configuracao/ConfigNFSe.cs:line 49
   at OpenAC.Net.NFSe.OpenNFSe.OnInitialize() in //src/OpenAC.Net.NFSe/OpenNFSe.cs:line 563
   at OpenAC.Net.Core.OpenComponent..ctor() in E:\Programacao\OpenAC .Net\OpenAC.Net.Core\src\OpenAC.Net.Core\OpenComponent.cs:line 68
   at OpenAC.Net.NFSe.OpenNFSe..ctor()
   at Panthera.DFe.Nfse.Inicializar()
   at Panthera.DFe.Nfse..ctor(Empresa emitente, Boolean incializar)
   at Panthera.UI.ViewModel.NotaServico_ViewModel.<ConsultarCommandExecute>b__142_0()
```

Ocorre em:
https://github.com/OpenAC-Net/OpenAC.Net.Core/blob/83afe1e4d6bd4c5d35db93b0ba4bdd545d294e8a/src/OpenAC.Net.Core/Extensions/AssemblyExtenssions.cs#L49

Na documentação temos: https://docs.microsoft.com/pt-br/dotnet/api/system.reflection.assembly.codebase?view=net-6.0

![image](https://user-images.githubusercontent.com/15945003/160300049-0340a0ad-62b1-4583-af0c-e1b6aa7946b7.png)

Acredito que basta substituir por Assembly.Location para manter o mesmo comportamento
https://docs.microsoft.com/pt-br/dotnet/api/system.reflection.assembly.location?view=net-6.0

**Comment by marcosgerene** [comment]
Só para documentação, fiz essa alteração no NFSe (onde aconteceu o erro) e obtive sucesso:

![image](https://user-images.githubusercontent.com/15945003/160301256-67e8ddda-4d78-4e1d-9629-a6b8972d7797.png)
